INSERT INTO SYS_ENTITY_AUDIT_CONFIGURATION (ID, ENTITY_NAME, NEEDS_AUDIT, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE)
 VALUES (ENAC_SEQ.NEXTVAL,'ae.rta.dls.backend.domain.prd.DrivingLicense',1,'DLS_SYSTEM', SYSDATE, 'DLS_SYSTEM', SYSDATE);

 INSERT INTO SYS_ENTITY_AUDIT_CONFIGURATION (ID, ENTITY_NAME, NEEDS_AUDIT, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE)
 VALUES (ENAC_SEQ.NEXTVAL,'ae.rta.dls.backend.domain.prd.MedicalFitness',1,'DLS_SYSTEM', SYSDATE, 'DLS_SYSTEM', SYSDATE);

 INSERT INTO SYS_ENTITY_AUDIT_CONFIGURATION (ID, ENTITY_NAME, NEEDS_AUDIT, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE)
 VALUES (ENAC_SEQ.NEXTVAL,'ae.rta.dls.backend.domain.prd.LearningFile',1,'DLS_SYSTEM', SYSDATE, 'DLS_SYSTEM', SYSDATE);

 INSERT INTO SYS_ENTITY_AUDIT_CONFIGURATION (ID, ENTITY_NAME, NEEDS_AUDIT, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE)
 VALUES (ENAC_SEQ.NEXTVAL,'ae.rta.dls.backend.domain.prd.Handbook',1,'DLS_SYSTEM', SYSDATE, 'DLS_SYSTEM', SYSDATE);

 INSERT INTO SYS_ENTITY_AUDIT_CONFIGURATION (ID, ENTITY_NAME, NEEDS_AUDIT, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE)
 VALUES (ENAC_SEQ.NEXTVAL,'ae.rta.dls.backend.domain.trn.Application',1,'DLS_SYSTEM', SYSDATE, 'DLS_SYSTEM', SYSDATE);

  INSERT INTO SYS_ENTITY_AUDIT_CONFIGURATION (ID, ENTITY_NAME, NEEDS_AUDIT, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE)
 VALUES (ENAC_SEQ.NEXTVAL,'ae.rta.dls.backend.domain.trn.ServiceRequest',1,'DLS_SYSTEM', SYSDATE, 'DLS_SYSTEM', SYSDATE);
