INSERT INTO SYS_AUTOMATED_JOB_CONFIG (ID, JOB_NAME, CRON, FIXED_DELAY, INITIAL_DELAY, FIXED_RATE, STATUS, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE)
 VALUES (AUJC_SEQ.NEXTVAL, 'ae.rta.dls.backend.job.trn.ApplicationRemovalJob', '0 0 0 * * *', NULL, NULL, NULL, 'ACTIVE', 'DLS_SYSTEM', SYSDATE, 'DLS_SYSTEM', SYSDATE);
