/*******************************************************
 ********** DOMAIN VALUES APTY_STATUS ******************
 *******************************************************
 *******************************************************/
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'ACTIVE','{"ar":"فعالة","en":"Active"}',1,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APTY_STATUS'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'INACTIVE','{"ar":"غير فعالة","en":"Inactive"}',2,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APTY_STATUS'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'UNDER_DEVELOPMENT','{"ar":"قيد التطوير","en":"Under development"}',3,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APTY_STATUS'),'system',SYSDATE,'system',SYSDATE);

/*******************************************************
 ********** DOMAIN VALUES APPL_STATUS ******************
 *******************************************************
 *******************************************************/
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'DRAFT','{"ar":"مسودة","en":"Draft"}',1,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_STATUS'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'UNDER_PROCESSING','{"ar":"قيد الإنجاز","en":"Under Processing"}',2,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_STATUS'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'COMPLETED','{"ar":"منجزة","en":"Completed"}',3,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_STATUS'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'REJECTED','{"ar":"مرفوض","en":"Rejected"}',4,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_STATUS'),'system',SYSDATE,'system',SYSDATE);

/****************************************************
 ******** DOMAIN VALUES (SERE_STATUS) ***************
 ****************************************************
 ****************************************************/
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'UNDER_PROCESSING','{"ar":"قيد الإنجاز","en":"Under Processing"}',1,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'SERE_STATUS'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'VERIFIED_AND_LOCKED','{"ar":"تم التحقق و الحجز","en":"Verified and Locked"}',2,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'SERE_STATUS'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'CONFIRMED','{"ar":"تمت الموافقة","en":"Confirmed"}',3,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'SERE_STATUS'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'REJECTED','{"ar":"مرفوض","en":"Rejected"}',4,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'SERE_STATUS'),'system',SYSDATE,'system',SYSDATE);

/*********************************************
 ******** DOMAIN VALUES (APPL_EXPERIENCE) ***********
 *********************************************
 *********************************************/
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'LESS_THAN_FIVE','{"ar":"اقل من 5 سنوات","en":"Less than 5 years"}',1,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_EXPERIENCE'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'MORE_THAN_FIVE','{"ar":"أكبر من 5 سنوات","en":"More than 5 years"}',2,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_EXPERIENCE'),'system',SYSDATE,'system',SYSDATE);

/**************************************************
 ******** DOMAIN VALUES (SERE_PHASE_TYPE) **************
 **************************************************
 **************************************************/
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'CUSTOMER_ELIGIBILITY','{"ar":"أهلية العميل","en":"Customer Eligibility"}',1,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'SERE_PHASE_TYPE'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'DRIVING_LEARNING_FILE_PROCESSING','{"ar":"إصدار ملف تعليم القيادة","en":"Driving Learning File Processing"}',2,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'SERE_PHASE_TYPE'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'DRIVING_LEARNING_FILE_AUDIT','{"ar":"تدقيق ملف تعليم القيادة","en":"Driving Learning File Audit"}',3,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'SERE_PHASE_TYPE'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'READY_FOR_CONTRACT_SIGN','{"ar":"بإنتظار توقيع العقد","en":"Ready For Constract Sign"}',4,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'SERE_PHASE_TYPE'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'EYE_TEST','{"ar":"فحص النظر","en":"Eye Test"}',5,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'SERE_PHASE_TYPE'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'THEORY_LECTURE','{"ar":"الدروس النظرية","en":"Theory Lecture"}',6,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'SERE_PHASE_TYPE'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'KNOWLEDGE_TEST','{"ar":"فحص التقييم","en":"Knowledge Test"}',7,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'SERE_PHASE_TYPE'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'PRACTICAL_TRAINING','{"ar":"الدروس العملية","en":"Practical Training"}',8,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'SERE_PHASE_TYPE'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'YARD_TEST','{"ar":"فحص الإصطفاف","en":"Yard Test"}',9,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'SERE_PHASE_TYPE'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'ADVANCED_PRACTICAL_TRAINING','{"ar":"الدروس العملية المتطورة","en":"Advanced Practical Training"}',10,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'SERE_PHASE_TYPE'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'ROAD_TEST','{"ar":"فحص الطريق","en":"Road Test"}',11,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'SERE_PHASE_TYPE'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'PRINT_LICENSE','{"ar":"طباعة الرخصة","en":"Print License"}',12,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'SERE_PHASE_TYPE'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'APPLICATION_REJECTION','{"ar":"رفض الطلب","en":"Application Rejecction"}',13,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'SERE_PHASE_TYPE'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'EXEMPTION_AUDITING','{"ar":"تدقيق الإعفاءات","en":"Excemption Auditing"}',14,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'SERE_PHASE_TYPE'),'system',SYSDATE,'system',SYSDATE);

/*******************************************************
 ********** DOMAIN VALUES (APVI_VIOLATION_LEVEL) ************
 *******************************************************/
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'BLOCKER','{"ar":"مانع","en":"Blocker"}',1,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APVI_VIOLATION_LEVEL'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'WARNING','{"ar":"تحذير","en":"Warning"}',2,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APVI_VIOLATION_LEVEL'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'INFO','{"ar":"معلومة","en":"Info"}',3,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APVI_VIOLATION_LEVEL'),'system',SYSDATE,'system',SYSDATE);

/*******************************************************
 ********** DOMAIN VALUES (AUJC_STATUS) ****************
 *******************************************************/
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'ACTIVE','{"ar":"فعال","en":"Active"}',1,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'AUJC_STATUS'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'INACTIVE','{"ar":"غير فعال","en":"Inactive"}',2,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'AUJC_STATUS'),'system',SYSDATE,'system',SYSDATE);

/*******************************************************
 ********** DOMAIN VALUES (LICA_STATUS) ****************
 *******************************************************/
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'ACTIVE','{"ar":"فعال","en":"Active"}',1,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'LICA_STATUS'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'INACTIVE','{"ar":"غير فعال","en":"Inactive"}',2,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'LICA_STATUS'),'system',SYSDATE,'system',SYSDATE);

/*******************************************************
 ********** DOMAIN VALUES (SEGR_STATUS) ****************
 *******************************************************/
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'ACTIVE','{"ar":"فعال","en":"Active"}',1,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'SEGR_STATUS'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'INACTIVE','{"ar":"غير فعال","en":"Inactive"}',2,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'SEGR_STATUS'),'system',SYSDATE,'system',SYSDATE);

/*******************************************************
 ********** DOMAIN VALUES (SERV_STATUS) ****************
 *******************************************************/
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'ACTIVE','{"ar":"فعال","en":"Active"}',1,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'SERV_STATUS'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'INACTIVE','{"ar":"غير فعال","en":"Inactive"}',2,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'SERV_STATUS'),'system',SYSDATE,'system',SYSDATE);

/*******************************************************
 ********** DOMAIN VALUES (VETY_STATUS) ****************
 *******************************************************/
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'ACTIVE','{"ar":"فعال","en":"Active"}',1,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'VETY_STATUS'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'INACTIVE','{"ar":"غير فعال","en":"Inactive"}',2,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'VETY_STATUS'),'system',SYSDATE,'system',SYSDATE);

/*******************************************************
 ********** DOMAIN VALUES (APPL_EYE_TEST_RESULT) *************
 *******************************************************/
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'NOT_REQUIRED','{"ar":"غير مطلوب","en":"Not required"}',1,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_EYE_TEST_RESULT'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'PENDING','{"ar":"مطلوب و بانتظار نتيجة الفحص","en":"Required and waiting for result"}',2,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_EYE_TEST_RESULT'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'FULFILLED','{"ar":"تم التأكد من نتيجة الفحص","en":"Required and fulfilled"}',3,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_EYE_TEST_RESULT'),'system',SYSDATE,'system',SYSDATE);

/*******************************************************
 ********** DOMAIN VALUES (APPL_DRIVING_SCHOOL_REVIEW_STATUS) *************
 *******************************************************/
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'PENDING','{"ar":"مطلوب و بانتظار تدقيق الطلب في المعهد","en":"Required and waiting audit from driving school"}',1,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_DRIVING_SCHOOL_REVIEW_STATUS'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'ACCEPTED','{"ar":"مقبول","en":"Accepted"}',2,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_DRIVING_SCHOOL_REVIEW_STATUS'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'REJECTED','{"ar":"مرفوض","en":"Rejected"}',3,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_DRIVING_SCHOOL_REVIEW_STATUS'),'system',SYSDATE,'system',SYSDATE);

/*******************************************************
 ********** DOMAIN VALUES (APPL_RTA_REVIEW_STATUS) *************
 *******************************************************/
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'PENDING','{"ar":"مطلوب و بانتظار تدقيق الطلب من قبل موظف الهيئة","en":"Required and waiting audit from RTA employee"}',1,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_RTA_REVIEW_STATUS'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'ACCEPTED','{"ar":"مقبول","en":"Accepted"}',2,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_RTA_REVIEW_STATUS'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'REJECTED','{"ar":"مرفوض","en":"Rejected"}',3,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_RTA_REVIEW_STATUS'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'NOT_REQUIRED','{"ar":"غير مطلوب","en":"Not required"}',4,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_RTA_REVIEW_STATUS'),'system',SYSDATE,'system',SYSDATE);

/*******************************************************
 ********** DOMAIN VALUES (APPL_NOC_TYPE) *************
 *******************************************************/
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'REQUIRED','{"ar":"مطلوب","en":"Required"}',1,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_NOC_TYPE'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'NOT_REQUIRED','{"ar":"غير مطلوب","en":"Not required"}',2,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_NOC_TYPE'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'FULFILLED_ELECTRONIC','{"ar":"تم التحميل الالكتروني","en":"Fulfilled noc electronic"}',3,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_NOC_TYPE'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'FULFILLED_MANUAL','{"ar":"تم التحميل اليدوي","en":"Fulfilled noc manual"}',4,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_NOC_TYPE'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'FULFILLED_MANUAL_REVIEWED','{"ar":"تم التدقيق المرفقات من المعهد","en":"Fulfilled and reviewed manual"}',5,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_NOC_TYPE'),'system',SYSDATE,'system',SYSDATE);

/*******************************************************
 ********** DOMAIN VALUES (APPL_TEST_RESULT) *************
 *******************************************************/
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'NOT_REQUIRED','{"ar":"غير مطلوب","en":"Not required"}',1,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_TEST_RESULT'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'PENDING','{"ar":"مطلوب و بانتظار نتيجة الفحص","en":"Required and waiting for result"}',2,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_TEST_RESULT'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'FULFILLED','{"ar":"تم التأكد من نتيجة الفحص","en":"Required and fulfilled"}',3,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_TEST_RESULT'),'system',SYSDATE,'system',SYSDATE);

/*******************************************************
 ********** DOMAIN VALUES (APPL_TEST_TYPE) *************
 *******************************************************/
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'THEORY','{"ar":"فحص نظري","en":"Theory test"}',1,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_TEST_TYPE'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'YARD','{"ar":"فحص ساحه","en":"Yard test"}',2,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_TEST_TYPE'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'ROAD','{"ar":"فحص طريق","en":"Road test"}',3,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_TEST_TYPE'),'system',SYSDATE,'system',SYSDATE);

/*******************************************************
 ********** DOMAIN VALUES (APPL_TEST_STATUS) *************
 *******************************************************/
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'REQUIRED','{"ar":"مطلوب","en":"Required"}',1,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_TEST_STATUS'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'NOT_REQUIRED','{"ar":"غير مطلوب","en":"Not Required"}',2,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_TEST_STATUS'),'system',SYSDATE,'system',SYSDATE);

/*******************************************************
 ********** DOMAIN VALUES APPL_CLEARANCE_STATUS ******************
 *******************************************************
 *******************************************************/
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'PENDING','{"ar":" الانتظار","en":"Pending"}',1,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_CLEARANCE_STATUS'),'system',SYSDATE,'system',SYSDATE);
INSERT INTO SYS_DOMAIN_VALUE (ID,VALUE,DESCRIPTION,SORT_ORDER,DOMAIN_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE) VALUES(DOVA_SEQ.NEXTVAL,'ADDED','{"ar":"تمت الاضافة","en":"Added"}',2,(SELECT ID FROM SYS_DOMAIN WHERE CODE = 'APPL_CLEARANCE_STATUS'),'system',SYSDATE,'system',SYSDATE);
