UPDATE SDM_LICENSE_CATEGORY
 SET SORT_ORDER = 1
WHERE CODE = 'VCL_ID_4';

UPDATE SDM_LICENSE_CATEGORY
 SET SORT_ORDER = 2
WHERE CODE = 'VCL_ID_3';

UPDATE SDM_LICENSE_CATEGORY
 SET SORT_ORDER = 3
WHERE CODE = 'VCL_ID_1';

UPDATE SDM_LICENSE_CATEGORY
 SET SORT_ORDER = 4
WHERE CODE = 'VCL_ID_5';
